### ISSUE TITLE
Can't port to C# due to 'MotionFilter' does not implement interface member 'IFilter.doFilter(double)'

### ISSUE THREAD

**Issue by seymurkarimov** [shoarai/WashoutFilter#2]
Many thanks for great job!

Trying to port to C# but stuck at 'MotionFilter' does not implement interface member 'IFilter.doFilter(double)'

Looked into sources and couldn't manage to find declaration in MotionFilter. Meanwhile there is declaration for IWashoutFilter in WashoutFilter. 

Please advise.

27.10.2017 Update: 
Error message was as below:
 The member 'Sample_rotationHighPassFilter.doFilter(double)' does not hide an inherited member. The new keyword is not required

The same for translation filters.

Managed to solve by adding: 

public double doFilter(double input0)
    {
       return input0;//do nothing
    }

in MotionFilter class.

and by changing doFilter declaration in Sample_rotationHighPassFilter to something like:

public new double doFilter(double input0)

**Comment by shoarai** [comment]
'MotionFilter' is an abstract class and its child classes must have 'doFilter(double)'.
Please refer to the sample classes in 'example/MotionFilter.h'.
Thank you!

**Comment by seymurkarimov** [comment]
Thanks for great job!

**Comment by shoarai** [comment]
Actually, you don't need to use 'MotionFilter' and can just make child classes of 'IFilter'.
I made it in Go language. Please refer this repository.
https://github.com/shoarai/washout
